package main

import "./algorithm"

func CheckMessageFull(foundString string) string {
  algorithm.FoundBASE32(foundString)
  algorithm.FoundBASE64(foundString)
  algorithm.FoundTIGER192(foundString)
  algorithm.FoundSHAKE128_224(foundString)
  algorithm.FoundSHAKE128_256(foundString)
  algorithm.FoundSHAKE128_384(foundString)
  algorithm.FoundSHAKE128_512(foundString)
  algorithm.FoundSHAKE256_224(foundString)
  algorithm.FoundSHAKE256_256(foundString)
  algorithm.FoundSHAKE256_384(foundString)
  algorithm.FoundSHAKE256_512(foundString)
  algorithm.FoundKECCAK224(foundString)
  algorithm.FoundKECCAK256(foundString)
  algorithm.FoundKECCAK384(foundString)
  algorithm.FoundKECCAK512(foundString)
  algorithm.FoundCRC32ieee(foundString)
  algorithm.FoundCRC64ecma(foundString)
  algorithm.FoundCRC64iso(foundString)
  algorithm.FoundADLER32(foundString)
  algorithm.FoundBLAKE2s256(foundString)
  algorithm.FoundBLAKE2b256(foundString)
  algorithm.FoundBLAKE2b384(foundString)
  algorithm.FoundBLAKE2b512(foundString)
  algorithm.FoundRIPEMD160(foundString)
  algorithm.FoundMD2(foundString)
  algorithm.FoundMD4(foundString)
  algorithm.FoundMD5(foundString)
  algorithm.FoundSHA1(foundString)
  algorithm.FoundSHA224(foundString)
  algorithm.FoundSHA256(foundString)
  algorithm.FoundSHA384(foundString)
  algorithm.FoundSHA512(foundString)
  algorithm.FoundSHA512_224(foundString)
  algorithm.FoundSHA512_256(foundString)
  algorithm.FoundSHA3_224(foundString)
  algorithm.FoundSHA3_256(foundString)
  algorithm.FoundSHA3_384(foundString)
  algorithm.FoundSHA3_512(foundString)
  algorithm.FoundFNV32(foundString)
  algorithm.FoundFNV32a(foundString)
  algorithm.FoundFNV64(foundString)
  algorithm.FoundFNV64a(foundString)
  algorithm.FoundFNV128(foundString)
  algorithm.FoundFNV128a(foundString)
  return foundString
}
