#!/usr/bin/env bash

echo "~~~~~~~~~~"
echo "checking, please wait..."
echo "~~~~~~~~~~"

while [ -n "$1" ]
do
  case "$1" in
    -m) go run message.go ;;
    -f) go run file.go $2 ;;
  esac
  shift
done
